### ISSUE TITLE
Music categories and their respective filters

### ISSUE THREAD

**Issue by ChrisTVH** [Beastwick18/nyaa#1]
Could you include these please?

**Comment by Beastwick18** [comment]
Like an All Audio, Audio Lossless, and Audio Lossy category?

**Comment by ChrisTVH** [comment]
Yes, those are the ones I am referring to.

**Comment by Beastwick18** [comment]
Cool. I'll get that added soon.

**Comment by Beastwick18** [comment]
Done, added with #2
