### ISSUE TITLE
Compilation Error on macOS: Unresolved Imports for linux_clipboard in cli_clipboard

### ISSUE THREAD

**Issue by roadsidev** [Beastwick18/nyaa#13]
When attempting to build the project with `cargo build --release` on macOS, the compiler throws an error for unresolved imports related to `linux_clipboard` in the `cli_clipboard` module. This seems to be due to platform-specific code that is not compatible with macOS.

Error message:
error[E0432]: unresolved imports `cli_clipboard::linux_clipboard`, `cli_clipboard::x11_clipboard`
...

![image](https://github.com/Beastwick18/nyaa/assets/6503047/8a0c3d87-fe40-453c-a2d6-9cd24a42cdb0)

Steps to Reproduce:
1. Run `cargo build --release` on macOS.

Expected Behavior:
The project should compile without errors.

Actual Behavior:
Compilation fails due to the unresolved imports for Linux-specific clipboard functionality.

I have submitted a Pull Request that addresses this issue: https://github.com/Beastwick18/nyaa/pull/14

I have resolved this issue by implementing conditional compilation based on the target_os. Although I have little to no experience in Rust, I hope my pull request will serve as a starting point. I managed to build the project on Windows, Linux, and macOS without any errors or warnings.

**Comment by roadsidev** [comment]
What's odd is that installing nyaa with `cargo install nyaa` works perfectly, but it fails when building from the source. I don't know what causes this issue.

**Comment by Beastwick18** [comment]
Very strange issue. No clue why that's happening. I haven't tested nyaa on macOS at all, so seeing that only one thing has broken (so far) is somewhat relieving 😅

**Comment by roadsidev** [comment]
I also tried building this on windows and the same error! but with my PR it fixes it. I tested the clipboard and it works fine 

![image](https://github.com/Beastwick18/nyaa/assets/6503047/494db7f2-0a56-4ec0-9765-0a9009fba35d)

**Comment by roadsidev** [comment]
> Very strange issue. No clue why that's happening. I haven't tested nyaa on macOS at all, so seeing that only one thing has broken (so far) is somewhat relieving 😅

It's working fine so far! I only started using it yesterday thanks to the Reddit post. If I find more issues, I'll be reporting and hopefully contribute to fix them

**Comment by Beastwick18** [comment]
Huh yeah I get the same error too on the previous commit. Your fix does seem to have fixed it for me too, though.

It's likely some conditional compilation that is completely omitting x11_clipboard and linux_clipboard.

> It's working fine so far! I only started using it yesterday thanks to the Reddit post. If I find more issues, I'll be reporting and hopefully contribute to fix them

Glad everything else is working so far. Feel free to make any contributions! :)

**Comment by Beastwick18** [comment]
Going to go ahead and close this since everything is now working. Thanks again for contributing :)
