### ISSUE TITLE
byte index 51 is not a char boundary

### ISSUE THREAD

**Issue by mosubpink** [Beastwick18/nyaa#15]
nyaa not runnig after i update it to last verison it gave the error : 
```
thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.26.2/src/text/line.rs:477:59:
                              byte index 51 is not a char boundary; it is inside 'о' (bytes 50..52) of `Sentai Dai Shikkaku | Боевой отряд «Полный провал» | Go! Go! Loser Ranger! [ТВ-1] [2024] [04 of 12] [WEBRip] [1080p] [RUS + JAP]`
                                 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
 
![Screenshot from 2024-04-30 19-49-25](https://github.com/Beastwick18/nyaa/assets/126292146/5eb4f6c4-427a-4f6f-805a-21a513c0cdbe)

**Comment by Beastwick18** [comment]
I'm not able to replicate this on v0.8.0. This is the version you are running right? You can check with `nyaa -V`. Does this happen every time the program is launched?

**Comment by Beastwick18** [comment]
Ah nevermind, I was able to replicate it, but I'm not sure of whats causing it. I'll look into this, but it seems to not happen on the up to date main branch. So whatever it was might already be fixed, but unreleased.

**Comment by Beastwick18** [comment]
Did some further digging, looks like this is an upstream issue with ratatui: ratatui-org/ratatui#1032

I'll push a fix soon, hopefully all that has to be done is to downgrade ratatui until it gets fixed upstream.

**Comment by Beastwick18** [comment]
This is now fixed on main, and the fix will be in the next release. In the meantime, if you want to build with cargo to get the fix earlier you can use:
```sh
cargo install --git https://github.com/Beastwick18/nyaa
```
Make sure you have rust version >=1.75 installed first.
