### ISSUE TITLE
Issue with Torrent Download on Subsequent Attempts

### ISSUE THREAD

**Issue by Hikki88** [Beastwick18/nyaa#23]
### Issue Description:

- When selecting a torrent and confirming it for download, the process succeeds only the first time. Subsequent attempts result in errors.

### Actual Error Message:

```
Failed to get SID: 
Failed to get cookie from qBittorrent: Ok. 
```

### Screenshot:

![error](https://github.com/Beastwick18/nyaa/assets/174235034/054ad2a0-1803-49ad-94c4-f22c95ff7e65)

**Comment by Hikki88** [comment]
Please let me know if you need any configuration details, although I haven't tweaked it a lot.

**Comment by Beastwick18** [comment]
Commit 0472a1c should have fixed this. It hasn't been released yet so if you're on the latest version (v0.9.0) it is broken. v0.9.1 should be out very soon once I've finished documentation

**Comment by Hikki88** [comment]
Ah okay, I should've gone through the commit history once I guess.
I looked at the few closed issues before posting this.
Thanks for the fast reply. Should I close this or would you like to link this to the release before closing it?

**Comment by Beastwick18** [comment]
It's all good I'll go ahead and close it. I plan on having the release out today since its ~99% done.
