### ISSUE TITLE
what does this mean ?

### ISSUE THREAD

**Issue by sachinchaudhary1808** [Beastwick18/nyaa#26]
![image](https://github.com/user-attachments/assets/2bd7a62e-b045-41a0-8a78-7cc62804f557)

**Comment by Beastwick18** [comment]
It means that the connection was closed by nyaa.si. It might be blocked in your country. Are you able to open that link in a normal web browser?

**Comment by Beastwick18** [comment]
In that case you'll want to use one of the proxies. The [ReadMe](https://github.com/Beastwick18/nyaa#-proxies) has a section on it. All you should have to do is add to your `config.toml`:
```toml
[source.nyaa]
base_url = "nyaa.land"
```

or replace nyaa.land with any other working proxy from the [list of proxies](https://nyaatorrents.info/#proxy)

**Comment by sachinchaudhary1808** [comment]
> In that case you'll want to use one of the proxies. The [ReadMe](https://github.com/Beastwick18/nyaa#-proxies) has a section on it. All you should have to do is add to your `config.toml`:
> ```toml
> [source.nyaa]
> base_url = "nyaa.land"
> ```
> 
> or replace nyaa.land with any other working proxy from the [list of proxies](https://nyaatorrents.info/#proxy)

Okay thanks, i will try this tomorrow

**Comment by Beastwick18** [comment]
Going to go ahead and close this as using a proxy is the known solution
