### ISSUE TITLE
Tui text is white even in light mode

### ISSUE THREAD

**Issue by SeseMueller** [Beastwick18/nyaa#30]
I installed nyaa today fresh via cargo and on first launch couldn't see anything because the primary text color was white, not black.

I see that few people use light mode given that this issue was not mentioned before, but it would still be nice to be able to use light mode.

I suggest checking the terminal's preferred color scheme (light/dark) and coloring the TUI accordingly.

**Comment by Beastwick18** [comment]
The "Default" theme should be using ANSI codes, which should match your terminals theme. By default, it uses whatever is defined as "White" (`\e[0;37m`) for default text. You could make a custom theme which uses either exact rgb values, or named colors to match your terminal by creating a theme in `~/.config/nyaa/themes/` or `%appdata%\nyaa\config\themes\`

Theres more info on the [Themes wiki page](https://github.com/Beastwick18/nyaa/wiki/User%E2%80%90defined-Themes)

Something like this works for me:
```toml
# File `~/.config/nyaa/themes/white.toml`
name = "White Theme"
bg = "Reset"
fg = "Black"
border = "Plain"
border_color = "Black"
border_focused_color = "Cyan"
hl_bg = "Gray"
solid_bg = "DarkGray"
solid_fg = "White"
success = "Green"
error = "Red"
info = "Green"
warning = "Yellow"
```
