### ISSUE TITLE
rqbit default config in wiki doesn't work

### ISSUE THREAD

**Issue by Disonantemus** [Beastwick18/nyaa#32]
[rqbit default config](https://github.com/Beastwick18/nyaa/wiki/rqbit#default-config)

~~~ocaml
# Your config in ~/.config/nyaa/config.toml or %appdata%\nyaa\config\config.toml
# ...
download_client = "rqbit"
# ...

[client.rqbit]
base_url = "http://localhost:3030" # required
use_magnet = true # optional, true by default
overwrite = false # optional
output_folder = "~/Downloads/" # optional
~~~

With default config, I can see rqbit downloading the file in terminal window and web, but is not in expected location (~/Downloads), when downloading or finished. Maybe the file is downloaded but to another location?

---

### Workaround1:

Because it is optional, works when removing this line:

~~~ocaml
output_folder = "~/Downloads/" # optional
~~~

---

### Workaround2:

If  I change that line to include full path, works as expected, like this:

~~~ocaml
output_folder = "/home/user/Downloads/"
~~~

---

~~~ocaml
kernel: 6.6.52-1-lts
shell: bash 5.2.37
term: tmux
~~~

**Comment by Beastwick18** [comment]
Looks like I had assumed rqbit would automatically expand paths like `~/Downloads` to `/home/user/Downloads`. c496c50 should fix this.

**Comment by Disonantemus** [comment]
I found downloaded files with default config, they are in:
~~~ocaml
~/Downloads/~/Downloads
~~~
maybe rqbit think like this: because is not a full path and server was started with:

~~~ocaml
rqbit server start /home/user/Downloads
~~~

it creates a subfolder inside "download folder" specified when launching the server.

**Comment by Beastwick18** [comment]
Yep, I think by default paths that dont have a leading `/` will be considered relative paths.

Closing this as the issue seems to be resolved through my testing.

A release with this change won't be out for a while since I'm working on a rewrite for 0.10. Though I may end up making a 0.9.2 release in the meantime if more changes happen.
