### ISSUE TITLE
version `GLIBC_2.38' not found

### ISSUE THREAD

**Issue by Avichal1234** [Beastwick18/nyaa#4]
![Screenshot from 2024-02-26 23-40-41](https://github.com/Beastwick18/nyaa/assets/86581604/1d707192-45af-4ff3-9742-83dd53d403e2)

Issue:
The program didn't work as expected on my pc (linux mint 21.3 cinnamon)

Steps to reproduce:
1. Download the program from the releases page
2. Try to run the program
3. Issue occurs

Please help me find a solution for this issue, I'd really like to try out your project but can't due to this problem. I tried to look up this issue online but almost all of them said that it was fixed after updating and restarting, but that still yields the same issue as in the attached screenshot. Help would be appreciated.

**Comment by Beastwick18** [comment]
I've just added a .deb release for v0.5.0 on the [releases](https://github.com/Beastwick18/nyaa/releases/tag/v0.5.0) page. It should be installable via:
```sh
sudo dpkg -i ./nyaa-0.5.0-x86_64.deb
```
on Ubuntu.

Let me know if that works for you :)

**Comment by Avichal1234** [comment]
Thanks a lot! I was able to install the package but it just gets stuck on loading, presumably because nyaa.si doesn't work in my location without a vpn, and I generally use a proxy site. Is there any way to change the source website that it scrapes from to a proxy, such as nyaa.land, instead of nyaa.si?

**Comment by Beastwick18** [comment]
Not at the moment, but the next release will have proxy support. It should be coming out very soon (sometime this week hopefully).

**Comment by Beastwick18** [comment]
Closing as there is now a debian release and proxy support
