### ISSUE TITLE
Double `get` request in Nyaa RSS

### ISSUE THREAD

**Issue by Amatrelan** [Beastwick18/nyaa#9]
You make twice request in Nyaa RSS.
First you you normal `get` method and later you create client and request again.

https://github.com/Beastwick18/nyaa/blob/eac6ccd3c5018e67fa83899ff47d804e3ed75474/src/source/nyaa_rss.rs#L62
https://github.com/Beastwick18/nyaa/blob/eac6ccd3c5018e67fa83899ff47d804e3ed75474/src/source/nyaa_rss.rs#L68

**Comment by Beastwick18** [comment]
Good catch, fixed with 457dbac
